modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "hexeffects"
version = "${version}"
displayName = "HexEffects"
logoFile = "icon.png"
authors = "krypton11"
description = '''
HexEffects addon for Hex Casting
'''

[[dependencies.hexeffects]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexeffects]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexeffects]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexeffects]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"
